### ISSUE TITLE
Application throws an error on running

### ISSUE THREAD

**Issue by vitortalaia** [OptimalBits/livef1.in#1]
Hi,

I'm trying to run this app to understand how your other module 'livef1' works, but it throws an error on line 8 column 30. Saying that 'require("connect").createServer" doesn't has this method.

**Comment by manast** [comment]
unfortunately the FIA has removed the access to the free data stream, so this project is useless now.

**Comment by vitortalaia** [comment]
Too bad, I wanted to use your module in a project for college. The FIA is destroying F1. :worried:
